apiVersion: v1
kind: Pod
metadata:
  name: hello-server
  labels:
    name: hello-server
spec:
  containers:
  - name: hello-server
    image: discofighter47/hello-server:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080

