version: 2.1
executors:
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build-server:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: |
            cd server
            docker build -t "$DOCKERHUB_USERNAME"/hello-server:latest .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push "$DOCKERHUB_USERNAME"/hello-server:latest
  
  build-frontend:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: |
            cd server
            docker build -t "$DOCKERHUB_USERNAME"/hello-frontend:latest .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push "$DOCKERHUB_USERNAME"/hello-frontend:latest

workflows:
  version: 2
  build_master:
    jobs:
      - build-server:
          filters:
            branches:
              only: master
      - build-frontend:
          filters:
            branches:
              only: master