apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: hello 
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: hello-frontend
        image: discofighter47/hello-frontend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
