apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: hello
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: hello-server
        image: discofighter47/hello-server:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
