name: hello-frontend
on: [push]
jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    steps:

    - name: set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12

    - name: check out code into the Go module directory
      uses: actions/checkout@v1

    - name: get dependencies
      run: |
        go get -v -t -d ./...

    - name: test
      run: |
        cd frontend
        go test -cover  ./...

  build:
    name: build
    runs-on: ubuntu-latest
    needs: [test]
    steps:

    - name: set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12

    - name: check out code into the Go module directory
      uses: actions/checkout@v1

    - name: get dependencies
      run: |
        go get -v -t -d ./...

    - name: build & push
      env:
        IMAGE: hello-frontend
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
      run: |
        commit=$(git rev-parse --short HEAD)
        cd frontend
        docker build -t "$DOCKERHUB_USERNAME"/"$IMAGE":$commit .
        echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        docker push "$DOCKERHUB_USERNAME"/"$IMAGE":$commit
