name: hello-server
on: [push]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12

    - name: check out code into current directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Test
      run: |
        cd server
        go test -cover  ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test]
    steps:

    - name: Check out code into current directory
      uses: actions/checkout@v1

    - name: Build & Push
      env:
        IMAGE: hello-server
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
      run: |
        commit=$(git rev-parse --short HEAD)
        cd server
        docker build -t "$DOCKERHUB_USERNAME"/"$IMAGE":$commit .
        echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        docker push "$DOCKERHUB_USERNAME"/"$IMAGE":$commit
